Aroma_Restaurent/Controllers/CakesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aroma_Restaurent.Models;

namespace Aroma_Restaurent.Controllers
{
    public class CakesController : Controller
    {
        private AromaContext db = new AromaContext();

        // GET: Cakes
        public ActionResult Index()
        {
            return View(db.Cakes.ToList());
        }

        // GET: Cakes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cake cake = db.Cakes.Find(id);
            if (cake == null)
            {
                return HttpNotFound();
            }
            return View(cake);
        }

        // GET: Cakes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cakes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Items,Description,Price")] Cake cake)
        {
            if (ModelState.IsValid)
            {
                db.Cakes.Add(cake);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cake);
        }

        // GET: Cakes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cake cake = db.Cakes.Find(id);
            if (cake == null)
            {
                return HttpNotFound();
            }
            return View(cake);
        }

        // POST: Cakes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Items,Description,Price")] Cake cake)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cake).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cake);
        }

        // GET: Cakes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cake cake = db.Cakes.Find(id);
            if (cake == null)
            {
                return HttpNotFound();
            }
            return View(cake);
        }

        // POST: Cakes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cake cake = db.Cakes.Find(id);
            db.Cakes.Remove(cake);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aroma_Restaurent/Controllers/CookiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aroma_Restaurent.Models;

namespace Aroma_Restaurent.Controllers
{
    public class CookiesController : Controller
    {
        private AromaContext db = new AromaContext();

        // GET: Cookies
        public ActionResult Index()
        {
            return View(db.Cookies.ToList());
        }

        // GET: Cookies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooky cooky = db.Cookies.Find(id);
            if (cooky == null)
            {
                return HttpNotFound();
            }
            return View(cooky);
        }

        // GET: Cookies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cookies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Item,Description,Price")] Cooky cooky)
        {
            if (ModelState.IsValid)
            {
                db.Cookies.Add(cooky);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cooky);
        }

        // GET: Cookies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooky cooky = db.Cookies.Find(id);
            if (cooky == null)
            {
                return HttpNotFound();
            }
            return View(cooky);
        }

        // POST: Cookies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Item,Description,Price")] Cooky cooky)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cooky).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cooky);
        }

        // GET: Cookies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cooky cooky = db.Cookies.Find(id);
            if (cooky == null)
            {
                return HttpNotFound();
            }
            return View(cooky);
        }

        // POST: Cookies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cooky cooky = db.Cookies.Find(id);
            db.Cookies.Remove(cooky);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aroma_Restaurent/Controllers/PastriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aroma_Restaurent.Models;

namespace Aroma_Restaurent.Controllers
{
    public class PastriesController : Controller
    {
        private AromaContext db = new AromaContext();

        // GET: Pastries
        public ActionResult Index()
        {
            return View(db.Pastries.ToList());
        }

        // GET: Pastries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastry pastry = db.Pastries.Find(id);
            if (pastry == null)
            {
                return HttpNotFound();
            }
            return View(pastry);
        }

        // GET: Pastries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pastries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Item,Description,Price")] Pastry pastry)
        {
            if (ModelState.IsValid)
            {
                db.Pastries.Add(pastry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pastry);
        }

        // GET: Pastries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastry pastry = db.Pastries.Find(id);
            if (pastry == null)
            {
                return HttpNotFound();
            }
            return View(pastry);
        }

        // POST: Pastries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Item,Description,Price")] Pastry pastry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pastry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pastry);
        }

        // GET: Pastries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pastry pastry = db.Pastries.Find(id);
            if (pastry == null)
            {
                return HttpNotFound();
            }
            return View(pastry);
        }

        // POST: Pastries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pastry pastry = db.Pastries.Find(id);
            db.Pastries.Remove(pastry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aroma_Restaurent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aroma Bakery </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



</head>
<!--Ishan Sharma (#300856455)
    Solanky Thareja (#300869859)
    MVC Restaurant - Aroma Bakery
    Assignment-2
-->
<body style="background-color:lightpink">
    
    <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink("Aroma Bakery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                   
                    <li><img src="~/Assests/vector_cake_food_logo.png" width="55" height="45" /></li>
                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home fa-lg" aria-hidden="true"></i><b> Home</b></a></li>
                    
                    <li><a href="@Url.Action("Contact", "Home")"><i class="fa fa-phone fa-lg" aria-hidden="true"></i><b> Contact</b></a></li> 

                </ul>
                <ul class="nav navbar-nav navbar-right">                    
                    <li><a href="@Url.Action("Index", "Cakes")"><i class="fa fa-birthday-cake" aria-hidden="true"></i> <b>Cakes</b></a></li>
                    <li><a href="@Url.Action("Index", "Pastries")"><i class="fa fa-cutlery" aria-hidden="true"></i><b> Pastries</b></a></li>
                    <li><a href="@Url.Action("Index", "Cookies")"><i class="fa fa-coffee" aria-hidden="true"></i> <b>Cookies</b></a></li>
               </ul>


            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <!-- Footer Bar -->
        <footer role="contentinfo">
            <nav class="navbar navbar-light navbar-fixed-bottom" style="background-color:#000000; color:deeppink">
                <div class="container">
                    <marquee id="marquee_speed" scrollamount="4" onmouseover=this.stop(); onmouseout=this.start(); scrolldelay="40"> <h3>&copy; <img src="~/Assests/vector_cake_food_logo.png" width="45" height="40" /><b>Aroma Bakery Ltd. | Toronto | Ontario | Canada</b> </h3>
                </div>
            </nav>
            </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>